// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_plan_version.test.ts.

/** The version of the `@ggdna/dna-plan` package. */
export const dnaPlanVersion = '0.3.0';
